<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class SalesOrder extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('sales_order', function (Blueprint $table){
            $table->increments('entity_id');
            $table->string('state')->unsigned()->index();
            $table->string('status')->unsigned()->index();
            $table->string('coupon_code');
            $table->string('protect_code');
            $table->string('shipping_description');
            $table->string('is_virtual');
            $table->string('store_id')->unsigned()->index();
            $table->string('customer_id')->unsigned()->index();
            $table->string('base_discount_amount');
            $table->string('base_discount_canceled');
            $table->string('base_discount_invoiced');
            $table->string('base_discount_refunded');
            $table->string('base_grand_total');
            $table->string('base_shipping_amount');
            $table->string('base_shipping_canceled');
            $table->string('base_shipping_invoiced');
            $table->string('base_shipping_refunded');
            $table->string('base_shipping_tax_amount');
            $table->string('base_shipping_tax_refunded');
            $table->string('base_subtotal');
            $table->string('base_subtotal_canceled');
            $table->string('base_subtotal_invoiced');
            $table->string('base_subtotal_refunded');
            $table->string('base_tax_amount');
            $table->string('base_tax_canceled');
            $table->string('base_tax_invoiced');
            $table->string('base_tax_refunded');
            $table->string('base_to_global_rate');
            $table->string('base_to_order_rate');
            $table->string('base_total_canceled');
            $table->string('base_total_invoiced');
            $table->string('base_total_invoiced_cost');
            $table->string('base_total_offline_refunded');
            $table->string('base_total_online_refunded');
            $table->string('base_total_paid');
            $table->string('base_total_qty_ordered');
            $table->string('base_total_refunded');
            $table->string('discount_amount');
            $table->string('discount_canceled');
            $table->string('discount_invoiced');
            $table->string('discount_refunded');
            $table->string('grand_total');
            $table->string('shipping_amount');
            $table->string('shipping_canceled');
            $table->string('shipping_invoiced');
            $table->string('shipping_refunded');
            $table->string('shipping_tax_amount');
            $table->string('shipping_tax_refunded');
            $table->string('store_to_base_rate');
            $table->string('store_to_order_rate');
            $table->string('subtotal');
            $table->string('subtotal_canceled');
            $table->string('subtotal_invoiced');
            $table->string('subtotal_refunded');
            $table->string('tax_amount');
            $table->string('tax_canceled');
            $table->string('tax_invoiced');
            $table->string('tax_refunded');
            $table->string('total_canceled');
            $table->string('total_invoiced');
            $table->string('total_offline_refunded');
            $table->string('total_online_refunded');
            $table->string('total_paid');
            $table->string('total_qty_ordered');
            $table->string('total_refunded');
            $table->string('can_ship_partially');
            $table->string('can_ship_partially_item');
            $table->string('customer_is_guest');
            $table->string('customer_note_notify');
            $table->string('billing_address_id');
            $table->string('customer_group_id');
            $table->string('edit_increment');
            $table->string('email_sent')->unsigned()->index();
            $table->string('send_email')->unsigned()->index();
            $table->string('forced_shipment_with_invoice');
            $table->string('payment_auth_expiration');
            $table->string('quote_address_id');
            $table->string('quote_id')->unsigned()->index();
            $table->string('shipping_address_id');
            $table->string('adjustment_negative');
            $table->string('adjustment_positive');
            $table->string('base_adjustment_negative');
            $table->string('base_adjustment_positive');
            $table->string('base_shipping_discount_amount');
            $table->string('base_subtotal_incl_tax');
            $table->string('base_total_due');
            $table->string('payment_authorization_amount');
            $table->string('shipping_discount_amount');
            $table->string('subtotal_incl_tax');
            $table->string('total_due');
            $table->string('weight');
            $table->string('customer_dob');
            $table->string('increment_id');
            $table->string('applied_rule_ids');
            $table->string('base_currency_code');
            $table->string('customer_email');
            $table->string('customer_firstname');
            $table->string('customer_lastname');
            $table->string('customer_middlename');
            $table->string('customer_prefix');
            $table->string('customer_suffix');
            $table->string('customer_taxvat');
            $table->string('discount_description');
            $table->string('ext_customer_id')->unsigned()->index();
            $table->string('ext_order_id');
            $table->string('global_currency_code');
            $table->string('hold_before_state');
            $table->string('hold_before_status');
            $table->string('order_currency_code');
            $table->string('original_increment_id');
            $table->string('relation_child_id');
            $table->string('relation_child_real_id');
            $table->string('relation_parent_id');
            $table->string('relation_parent_real_id');
            $table->string('remote_ip');
            $table->string('shipping_method');
            $table->string('store_currency_code');
            $table->string('store_name');
            $table->string('x_forwarded_for');
            $table->string('customer_note');
            $table->string('total_item_count');
            $table->string('customer_gender');
            $table->string('discount_tax_compensation_amount');
            $table->string('base_discount_tax_compensation_amount');
            $table->string('shipping_discount_tax_compensation_amount');
            $table->string('base_shipping_discount_tax_compensation_amnt');
            $table->string('discount_tax_compensation_invoiced');
            $table->string('base_discount_tax_compensation_invoiced');
            $table->string('discount_tax_compensation_refunded');
            $table->string('base_discount_tax_compensation_refunded');
            $table->string('shipping_incl_tax');
            $table->string('base_shipping_incl_tax');
            $table->string('coupon_rule_name');
            $table->string('paypal_ipn_customer_notified');
            $table->string('gift_message_id');
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        //
    }
}
